name: Deploy to Reseller via FTP
on:
  push:
    branches:
      - main # Hangi dala push yapıldığında tetikleneceğini belirler
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Al (Checkout)
        uses: actions/checkout@v3
        
      - name: FTP ile Sunucuya Yükle
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            README.md
            SECURITY.md
            mysql.sql
            .env-EXAMPLE
            Kanallar.txt